---
title: "Checks for normality"
output: html_document
date: "2026-02-18"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}

library(ggplot2)
library(tidyverse)
alzheimers <- read.csv("~/riskcalc/data/alzheimers_disease_data.csv")

## BMI is fairly normal
alzheimers %>%
  ggplot(aes(x = BMI)) + geom_density(alpha = .5)
## AlcoholConsumption is fairly normal
alzheimers %>%
  ggplot(aes(AlcoholConsumption)) + geom_density(alpha = .5)
## PhyscialActivyt is fairly normal
alzheimers %>%
  ggplot(aes(PhysicalActivity)) + geom_density(alpha = .5)
## DietQuality
alzheimers %>%
  ggplot(aes(DietQuality)) + geom_density(alpha = .5)
## Sleep Quality
alzheimers %>%
  ggplot(aes(SleepQuality)) + geom_density(alpha = .5)
## Gender
alzheimers %>%
  ggplot(aes(Gender)) + geom_density
## Age
alzheimers %>%
  ggplot(aes(Age)) + geom_density(alpha = .5)
##Ethnicity is not a normal distribution
alzheimers %>%
  ggplot(aes(Ethnicity)) + geom_density(alpha = .5)
## Smoking
alzheimers %>%
  ggplot(aes(Smoking)) + geom_density(alpha = .5)


```



```{r}

library(ggplot2)
library(tidyverse)
library(shiny)
alzheimers <- read.csv("~/riskcalc/data/alzheimers_disease_data.csv")

alzheimers %>%
  ggplot(aes(Diagnosis, BMI, fill = Diagnosis)) + 
  geom_boxplot() + 
  ylim(0, 60)

alzheimers %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c(0, 1), labels = c("No Alzheimer's", "Alzheimer's"))) %>%
  ggplot(aes(Diagnosis, BMI, fill = Diagnosis)) + 
  geom_boxplot() + 
  ylim(15, 40)

alzheimers %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c(0, 1), labels = c("No Alzheimer's", "Alzheimer's"))) %>%
  ggplot(aes(Diagnosis, FunctionalAssessment, fill = Diagnosis)) + 
  geom_boxplot() + 
  ylim(0, 10)

alzheimers %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c(0, 1), labels = c("No Alzheimer's", "Alzheimer's"))) %>%
  ggplot(aes(Diagnosis, SleepQuality, fill = Diagnosis)) + 
  geom_boxplot() + 
  ylim(0, 10)

alzheimers %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c(0, 1), labels = c("No Alzheimer's", "Alzheimer's"))) %>%
  ggplot(aes(Diagnosis, Age, fill = Diagnosis)) + 
  geom_boxplot() + 
  ylim(30, 100)
                
 alzheimers %>%
  mutate(Diagnosis = factor(Diagnosis, levels = c(0, 1), labels = c("No Alzheimer's", "Alzheimer's"))) %>%
  ggplot(aes(Diagnosis, MMSE, fill = Diagnosis)) + 
  geom_boxplot() + 
  ylim(0, 35)
```
